### ISSUE TITLE
Hidden Enemies show up in the Carousel

### ISSUE THREAD

**Issue by roi007leaf** [death-save/combat-carousel#139]
**Is your feature request related to a problem? Please describe.**
Currently whenever an encounter is setup in the combat tracker it shows up in the carousel - even hidden enemies are shown, therefore we need an option as DMs to force the players carousel to not show up until we as Dms allow it
**Describe the solution you'd like**
A button for the DM to control the visibility state of the carousel of players
**Describe alternatives you've considered**
a setting that will show the carousel for players only after the DM has clicked start combat
**Additional context**
none

**Comment by eclarke12** [comment]
Thanks for the issue! Hidden combatants showing up is a bug for sure. I believe it's been recorded but I haven't gotten around to updating Combat Carousel for awhile.

**Comment by roi007leaf** [comment]
> Thanks for the issue! Hidden combatants showing up is a bug for sure. I believe it's been recorded but I haven't gotten around to updating Combat Carousel for awhile.

For sure! i still think the feature will be useful :-)

**Comment by eclarke12** [comment]
Combatants that are Hidden in the combat tracker should be correctly hidden in the Carousel in v0.3.0.
Since there is no control to prevent players opening the combat tracker, I'm not going to add one for Combat Carousel at this time beyond enabling/disabling the module.

If you are referring to Tokens you've set as hidden, this does not hide them in the default Combat tracker so Combat Carousel is no different in that sense.
